### ISSUE TITLE
gaming-twitch.com

### ISSUE THREAD

**Issue by notKnownn** [Discord-AntiScam/scam-links#100]
**URL**
gaming-twitch.com/getpremium

**Additional context**
that domain is being used to offer scam websites like /getpremium (I don't know how much sites does the domain have).

**Comment by actually-akac** [comment]
Hi, thank you for the submission. Added the the domain in commit https://github.com/Discord-AntiScam/scam-links/commit/970659bd58916291ca2bdd9c12b7572623d7b8f9.
