### ISSUE TITLE
[URL]

### ISSUE THREAD

**Issue by HEYYYYYYYYYYYYYYYYd15qd45d1** [Discord-AntiScam/scam-links#101]
**URL**
https://counter-strike.net/

**Additional context**
The counter strike site :)

**Comment by actually-akac** [comment]
Thanks for pointing out a false positive in the database. I've gone ahead and removed the domain from the lists in commit https://github.com/Discord-AntiScam/scam-links/commit/a5b54003ba240e825eddca323f3a8ebda93712c3.
