### ISSUE TITLE
h15t.cfd

### ISSUE THREAD

**Issue by NebraskyTheWolf** [Discord-AntiScam/scam-links#104]
**URL**
h15t.cfd

**Additional context**
![Screenshot_2024-03-22-06-49-21-303_com discord](https://github.com/Discord-AntiScam/scam-links/assets/95084549/dcf32dac-b995-4798-b112-ca5d5df43af1)

This is a steam Scam link

**Comment by actually-akac** [comment]
Thanks, added this domain into the phishing database in commit https://github.com/Discord-AntiScam/scam-links/commit/4a14afd331dcd245a76e7563273a241f84123030.
Jinak ahoj 🙂
