### ISSUE TITLE
uspb.uspsin.top

### ISSUE THREAD

**Issue by TheInternetSadDev** [Discord-AntiScam/scam-links#108]
**URL**
https://uspb.uspsin.top/pg

**Additional context**
tags: ['usps']

**Comment by actually-akac** [comment]
Thanks, while not directly related to Discord, I've still gone ahead and added the domain into the database in commit https://github.com/Discord-AntiScam/scam-links/commit/b31c1f8f96e170da43e5758cce759f77bcaea26f.
