### ISSUE TITLE
[new url] google.webaccess-alerts.net

### ISSUE THREAD

**Issue by TheInternetSadDev** [Discord-AntiScam/scam-links#109]
**URL**
https://google.webaccess-alerts.net/o/vz6ud9q6/ce35bb/c71cd1d0-dbaf-4ff6-b6ea-4e19d76635fd

**Additional context**
tags: ['google']

**Comment by actually-akac** [comment]
Thanks, while not directly related to Discord, I've still gone ahead and added the domain into the database in commit https://github.com/Discord-AntiScam/scam-links/commit/3e95aa6d3766024a91e415bf623cc9309f11fdf7.
