### ISSUE TITLE
[URL] gmail.infosecurityshop.com

### ISSUE THREAD

**Issue by TheInternetSadDev** [Discord-AntiScam/scam-links#110]
**URL**
https://gmail.infosecurityshop.com/q3p2nscm/57f70e/a1a210e5-d2ed-4f89-a561-f92e951d6d92

**Additional context**
Tags: ['google']

**Comment by TheInternetSadDev** [comment]
How could I contribute to the project? how can I help?(besides sending issues/links)

**Comment by actually-akac** [comment]
Thanks, while not directly related to Discord, I've still gone ahead and added the domain into the database in commit https://github.com/Discord-AntiScam/scam-links/commit/a41a3723ea3b7cc1bec0ca856e48cf7dcf0e127a.

I'm worried that there isn't much else that you could do to help us besides providing us with more URLs that aren't in the phishing database yet. I appreciate your interest.
