### ISSUE TITLE
[URL] imtoken-at.net

### ISSUE THREAD

**Issue by TheInternetSadDev** [Discord-AntiScam/scam-links#111]
**URL**
https://imtoken-at.net

**Additional context**
Tags: ['imtoken', 'crypto']

**Comment by actually-akac** [comment]
Thanks, I've gone ahead and added the domain into the database in commit https://github.com/Discord-AntiScam/scam-links/commit/ba109b2cfa813b5d2b9900ca8b386e857682992b.
