### ISSUE TITLE
[URL] mysterybox38726.vercel.app

### ISSUE THREAD

**Issue by TheInternetSadDev** [Discord-AntiScam/scam-links#112]
**URL**
https://mysterybox38726.vercel.app/
	
**Additional context**
Tags: ['crypto/wallet', 'opensea']

**Comment by actually-akac** [comment]
Thanks, I've gone ahead and added the domain into the database in commit https://github.com/Discord-AntiScam/scam-links/commit/e520fdd0daff96f4f9dbca85dced7cbc9ae8655a.
