### ISSUE TITLE
[URL] False Positive about satoshiprotocol.org

### ISSUE THREAD

**Issue by imfeng** [Discord-AntiScam/scam-links#113]
**URL**
`satoshiprotocol.org`

**Additional context**
"Satoshi Protocol" is the first CDP built on BTC Layer 2, it allows investors to deposit BTC and borrow stable-coin $SAT, Unleash trillion dollars of BTCFi

it is a legitimate project with a Total Value Locked (TVL) reaching as high as 1 million USD. This is not a scam website.

X: [SatoshiBEVM](https://x.com/SatoshiBEVM)
Defillama: [satoshi-protocol](https://defillama.com/protocol/satoshi-protocol#information)
Website: [https://www.satoshiprotocol.org/](https://www.satoshiprotocol.org/)

**Comment by imfeng** [comment]
#114 Create PR

**Comment by akacdev** [comment]
Thanks for bringing up the issue, I've gone ahead and removed the domain from the list in commit https://github.com/Discord-AntiScam/scam-links/commit/9723b6b7bcd4e17fd56c02cdc64b5c1ae73b4b76.
