### ISSUE TITLE
Remove official discord link

### ISSUE THREAD

**Issue by SkyLighted** [Discord-AntiScam/scam-links#23]
remove discordapp.com from list, its a real discord link.

**Comment by Nickwasused** [comment]
The Url "discordapp.com" is not in the list. Can you send the line number and Filename?

**Comment by SkyLighted** [comment]
![image](https://user-images.githubusercontent.com/43494452/152653483-3fa9a1e4-bec6-465d-94ef-ac2612327c04.png)

**Comment by Nickwasused** [comment]
"disçordapp.com" is not the same as "discordapp.com". The difference is the "ç" compared to "c".
