### ISSUE TITLE
Flavours

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Discord-AntiScam/scam-links#7]
Rick rolls for most people aren't really considered "bannable" which hinders the usablity... why not add flavours like StevenBlack's host files? https://github.com/StevenBlack/hosts

**Comment by MrKsiJ** [comment]
A good project, will it be updated?
I want to connect him to my bot so that he cleans the scams in the chat

**Comment by ThinLiquid** [comment]
We actually removed rick rolls

**Comment by ThinLiquid** [comment]
We may add flavours in the future.
