### ISSUE TITLE
[URL]

### ISSUE THREAD

**Issue by Sr-Muffin** [Discord-AntiScam/scam-links#73]
**URL**
Enter URL Here

**Additional context**
Here is a list of links that are not in "list.txt", I put it in a text document due to github's character limitation
[scam_links_discord.txt](https://github.com/Discord-AntiScam/scam-links/files/10325442/scam_links_discord.txt)

**Comment by actually-akac** [comment]
Thank you, I've added these domains into our database and updated the files.
