### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by SiamOfficial** [Discord-AntiScam/scam-links#76]
**URL**
twitch.tv

**Additional context**
Please for real, check the scam links and remove the legitimate websites. How come twitch.tv be a scam? Don't add links before checking properly:(

**Comment by SiamOfficial** [comment]
wrong nvm

**Comment by arceusxx** [comment]
probably due to the "witch.tv" domain on line 22386
if the code checks if the request contains one of the urls, "twitch.tv" will be considered as in the list because it contains "witch.tv".
