### ISSUE TITLE
All Grabify's, Custom Urls with Expiry 

### ISSUE THREAD

**Issue by S7NX** [Discord-AntiScam/scam-links#88]
**URL**
Enter URL Here
mymassive.yachts
stonks.boats
stonks.fun
toes.beauty
barefoot.pics
shareit.pics
gamer.tattoo
shipment.website
imagevault.cloud
sugma.mom
yum.mom
plz.life
massive.mom
massive.boats
mymassive.store
mymassive.top
gamer.hair
photovault.pics
bathtub.pics
foot.wiki
thisdomainislong.lol
gamergirl.pro
picshost.pics
pichost.pics
imghost.pics
imagehost.pics
toldyouso.lol
toldyouso.pics
screenshare.pics
myprivate.pics
noodshare.pics
dateing.club
shrekis.life
headshot.monster
progaming.monster
yourmy.monster
screenshot.best
gamingfun.me
catsnthing.com
catsnthings.fun
joinmy.site
fortnitechat.site
fortnight.space
stopify.co
**Additional context**
These are all the grabify's custom urls,
and these are its expirey

mymassive.yachts - (Domain expires: 2024-04-05)
stonks.boats - (Domain expires: 2024-04-05)
stonks.fun - (Domain expires: 2024-04-05)
toes.beauty - (Domain expires: 2024-04-05)
barefoot.pics - (Domain expires: 2024-04-05)
shareit.pics - (Domain expires: 2024-04-05)
gamer.tattoo - (Domain expires: 2024-04-05)
shipment.website - (Domain expires: 2024-04-05)
imagevault.cloud - (Domain expires: 2024-04-05)
sugma.mom - (Domain expires: 2024-04-05)
yum.mom - (Domain expires: 2024-04-05)
plz.life - (Domain expires: 2024-04-05)
massive.mom - (Domain expires: 2024-04-05)
massive.boats - (Domain expires: 2024-04-05)
mymassive.store - (Domain expires: 2024-04-05)
mymassive.top - (Domain expires: 2024-04-05)
gamer.hair - (Domain expires: 2024-04-05)
photovault.pics - (Domain expires: 2023-09-21)
bathtub.pics - (Domain expires: 2023-09-21)
foot.wiki - (Domain expires: 2023-09-21)
thisdomainislong.lol - (Domain expires: 2023-09-21)
gamergirl.pro - (Domain expires: 2023-09-21)
picshost.pics - (Domain expires: 2023-09-21)
pichost.pics - (Domain expires: 2023-09-21)
imghost.pics - (Domain expires: 2023-09-21)
imagehost.pics - (Domain expires: 2023-09-21)
toldyouso.lol - (Domain expires: 2023-09-21)
toldyouso.pics - (Domain expires: 2023-09-21)
screenshare.pics - (Domain expires: 2024-05-18)
myprivate.pics - (Domain expires: 2024-05-18)
noodshare.pics - (Domain expires: 2024-05-18)
dateing.club - (Domain expires: 2023-09-23)
shrekis.life - (Domain expires: 2023-09-26)
headshot.monster - (Domain expires: 2023-09-23)
progaming.monster - (Domain expires: 2023-09-23)
yourmy.monster - (Domain expires: 2023-09-23)
screenshot.best - (Domain expires: 2023-09-26)
gamingfun.me - (Domain expires: 2023-09-26)
catsnthing.com - (Domain expires: 2023-10-09)
catsnthings.fun - (Domain expires: 2023-10-09)
joinmy.site - (Domain expires: 2023-09-26)
fortnitechat.site - (Domain expires: 2023-09-26)
fortnight.space - (Domain expires: 2023-09-26)
stopify.co - (Domain expires: 2023-08-11)

**Comment by actually-akac** [comment]
Hi, we've currently decided not to add this chunk of domains as we're unsure whether this large amount of domains fits with our current malicious domains stored in the database. Thank you for your contribution.
