### ISSUE TITLE
[https://adfoc.us/] False Positive

### ISSUE THREAD

**Issue by HEYYYYYYYYYYYYYYYYd15qd45d1** [Discord-AntiScam/scam-links#89]
**URL**
[Enter URL Here](https://adfoc.us/)

**Additional context**
This site is not a phising site.

**Comment by actually-akac** [comment]
Hi, thanks for the contribution. I recall already dealing with these false positives in the past, but for some reason they are still in the repository. I've just removed Adfocus and Adfly from the lists again, hopefully for the final time.
