### ISSUE TITLE
[URL] fazeclan-prize.pro

### ISSUE THREAD

**Issue by HEYYYYYYYYYYYYYYYYd15qd45d1** [Discord-AntiScam/scam-links#94]
**URL**
fazeclan-prize.pro

**Additional context**
Evident scam

**Comment by actually-akac** [comment]
Thanks for your submission, added to the database in commit https://github.com/Discord-AntiScam/scam-links/commit/51e2844bc2c69e82944f9e4935dda3893e442dad.
