### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by neochaos42** [Discord-AntiScam/scam-links#95]
Hi as a uBlock Origin User, would it be possible to import this list into uBO as a block list https://github.com/gorhill/uBlock/wiki/Static-filter-syntax

**Comment by actually-akac** [comment]
Thanks for the suggestion. I've gone ahead and implemented this change. The uBlock Origin filter file is now available to be imported from https://raw.githubusercontent.com/Discord-AntiScam/scam-links/main/ublock_filter.txt.
