### ISSUE TITLE
[URL] Scam

### ISSUE THREAD

**Issue by HEYYYYYYYYYYYYYYYYd15qd45d1** [Discord-AntiScam/scam-links#96]
**URL**
steamcorumunity.ru
go2cup.com
steamcomnunitc.ru
steamcommunitc.com

**Additional context**
steamcorumunity.ru = Basic scam about steam
go2cup.com = Discord nitro scam
steamcomnunitc.ru = Basic scam about steam
steamcommunitc.com = Basic scam about steam

**Comment by HEYYYYYYYYYYYYYYYYd15qd45d1** [comment]
Another one 
botcaptcha-verify.site = Discord phising

**Comment by actually-akac** [comment]
Thanks, these domains have been added to the database.
