### ISSUE TITLE
[URL] False Positive

### ISSUE THREAD

**Issue by HEYYYYYYYYYYYYYYYYd15qd45d1** [Discord-AntiScam/scam-links#97]
**URL**
cloudfront.net

**Additional context**
This URL is used by gaming.amazon.com when this url is blocked the site becomes non-functional. (same for twitch, vrchat,dulingo and discordstatus.com)

**Comment by actually-akac** [comment]
Thanks for bringing this up, domain removed in commit https://github.com/Discord-AntiScam/scam-links/commit/c1790fb54bec641c6b86c0c9070000305b7bff94.
